version: 2.1

jobs:
  # Test
  build:
    docker:
      - image: adoptopenjdk/openjdk8:jdk8u222-b10-alpine-slim
    steps:
      - checkout
      - run: |
          apk add --no-cache ca-certificates
          cat */build.gradle.kts > .gradle-cache-key
      - restore_cache:
          keys:
            - gradle-DFAHLD-{{ checksum ".gradle-cache-key" }}
            - gradle-DFAHLD-
      - run: |
          ./gradlew test
      - save_cache:
          key: gradle-DFAHLD-{{ checksum ".gradle-cache-key" }}
          paths: ~/.gradle
      - run:
          command: |
            mkdir -p test-results/junit
            find */build/test-results/test/*.xml -type f -exec cp {} test-results/junit \;
          when: always
      - store_test_results:
          path: test-results
